### ISSUE TITLE
DFD Comments Feb 14

### ISSUE THREAD

**Issue by germonprez** [brian-hodges/ISQA3420#5]
Here are a few comments: 

1) I don't think that you need any of these arrows: 

<img width="150" alt="screen shot 2017-02-14 at 5 56 19 am" src="https://cloud.githubusercontent.com/assets/656208/22931677/5feef08e-f27a-11e6-9192-d9fb7aca6bdc.png">

2) This should include a policy request and old policy info could simply be something like requested policy info: 

<img width="773" alt="screen shot 2017-02-14 at 5 57 18 am" src="https://cloud.githubusercontent.com/assets/656208/22931713/8d5e2ed6-f27a-11e6-9e74-f2940e136aa5.png">

3) Are package policy and package compliance the same thing: 

<img width="584" alt="screen shot 2017-02-14 at 5 58 19 am" src="https://cloud.githubusercontent.com/assets/656208/22931737/a48a3154-f27a-11e6-9451-f3828050cc1c.png">

**Comment by a-hodges** [comment]
Item 2 addressed in DFD
Items 1 & 3 to be clarified in Data Dictionary
